import autoPlant

def itemLog(message):
	quick_print("")
	quick_print(message)
	quick_print("The number of items")
	quick_print("  - hay    :", num_items(Items.Hay))
	quick_print("  - wood   :", num_items(Items.Wood))
	quick_print("  - carrot :", num_items(Items.Carrot))
	quick_print("  - pumpkin:", num_items(Items.Pumpkin))

def compLog():
	quick_print("")
	quick_print("## complete Log")
	quick_print("Target Number")
	quick_print("  - hay    :", autoPlant.hayTargetNumber)
	quick_print("  - wood   :", autoPlant.woodTargetNumber)
	quick_print("  - carrot :", autoPlant.carrotTargetNumber)
	quick_print("  - pumpkin:", autoPlant.pumpkinTargetNumber)
	quick_print("Needs Number")
	quick_print("  - hay    :", autoPlant.hayNeedsNumber)
	quick_print("  - wood   :", autoPlant.woodNeedsNumber)
	quick_print("  - carrot :", autoPlant.carrotNeedsNumber)
	quick_print("  - pumpkin:", autoPlant.pumpkinNeedsNumber)
	quick_print("Planted Number")
	quick_print("  - grass :", autoPlant.grassPlantedNumber)
	quick_print("  - bush  :", autoPlant.bushPlantedNumber)
	quick_print("  - tree  :", autoPlant.treePlantedNumber)
	quick_print("  - carrot:", autoPlant.carrotPlantedNumber)
	quick_print("  - pumpkin", autoPlant.pumpkinPlantedNumber)
	quick_print("Harvest Number")
	quick_print("  - hay    :", autoPlant.hayHarvestNumber)
	quick_print("  - wood   :", autoPlant.woodHarvestNumber)
	quick_print("  - carrot :", autoPlant.carrotHarvestNumber)
	quick_print("  - pumpkin:", autoPlant.pumpkinHarvestNumber)
	quick_print("----")
	quick_print("Harvest Rate")
	quick_print("  - hay    :", autoPlant.hayHarvestRate)
	quick_print("  - wood   :", autoPlant.woodHarvestRate)
	quick_print("  - carrot :", autoPlant.carrotHarvestRate)
	quick_print("  - pumpkin:", autoPlant.pumpkinHarvestRate)
	quick_print("Entity Level")
	quick_print("  - carrot :", autoPlant.carrotLevel)
	quick_print("  - pumpkin:", autoPlant.pumpkinLevel)
