import autoPlant

def compLog():
	quick_print("")
	quick_print("## autoPlant Log")
	quick_print("Target Number")
	quick_print("  - hay    :", autoPlant.hayTargetNumber)
	quick_print("  - wood   :", autoPlant.woodTargetNumber)
	quick_print("  - carrot :", autoPlant.carrotTargetNumber)
	quick_print("  - punpkin:", autoPlant.punpkinTargetNumber)
	quick_print("Needs Number")
	quick_print("  - hay    :", autoPlant.hayNeedsNumber)
	quick_print("  - wood   :", autoPlant.woodNeedsNumber)
	quick_print("  - carrot :", autoPlant.carrotNeedsNumber)
	quick_print("  - punpkin:", autoPlant.punpkinNeedsNumber)
	quick_print("Planted Number")
	quick_print("  - grass :", autoPlant.grassPlantedNumber)
	quick_print("  - bush  :", autoPlant.bushPlantedNumber)
	quick_print("  - tree  :", autoPlant.treePlantedNumber)
	quick_print("  - carrot:", autoPlant.carrotPlantedNumber)
	quick_print("  - punpkin", autoPlant.punpkinPlantedNumber)
	quick_print("Harvest Number")
	quick_print("  - hay    :", autoPlant.hayHarvestNumber)
	quick_print("  - wood   :", autoPlant.woodHarvestNumber)
	quick_print("  - carrot :", autoPlant.carrotHarvestNumber)
	quick_print("  - punpkin:", autoPlant.punpkinHarvestNumber)
